Pin typescript to ~2.1.0 to stop build errors
The `package.json` setting `"typescript": "^2.1.0-dev.20160903"` allows
`typescript@2.6.2` to be installed. This results in hundreds of build errors.

Examples:
```
ERROR in WasmFiddle/node_modules/react-split-pane/node_modules/@types/react/index.d.ts
(3566,13): error TS2403: Subsequent variable declarations must have the same
type. Variable 'a' must be of type 'HTMLProps<HTMLAnchorElement>', but here
has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.

ERROR in WasmFiddle/node_modules/@types/react/index.d.ts
(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with
type 'ComponentLifecycle<P, S>'.
```

Dependencies need to be upgraded, but this allows the project to build on a new
machine in the meantime.

Versions:
```
$ node --version
v8.9.4
$ npm --version
5.6.0
```